create table Person (
                        id int generated by default as identity primary key,
                        full_name varchar(100) not null,
                        year_of_birth int not null
);

create table Book (
                      id int generated by default as identity primary key,
                      title varchar(100) not null,
                      author varchar(100) not null,
                      year int not null,
                      person_id int references Person(id) on delete set null
);